# Assignment
# We need to be able to search our LockedIn user base more quickly! Our users are complaining that the search bar 
# is painfully slow. You'll notice that if you run the code in its current state, it will take a very long time.
#
# The find_last_name function takes
#
# names_dict: a dictionary of first_name -> last_name.
# first_name: a string.
# If first_name is a key in the dictionary, find_last_name returns the associated last name. If the key is not 
# found, it returns None.
#
# Write the function so that it runs quickly! It should be O(1).

def find_last_name(names_dict, first_name):
    if first_name in names_dict:
        return names_dict[first_name]
    return None

# test cases
names_dict = {
    "John": "Doe",
    "Jane": "Smith",
    "Mike": "Jones",
    "Alice": "Brown",
    "Bob": "Davis",
    "Charlie": "Miller",
    "David": "Wilson",
    "Eve": "Moore",
    "Frank": "Taylor",
    "Grace": "Anderson",
    "Hank": "Thomas",
    "Ivy": "Jackson",
    "Jack": "White",
    "Kathy": "Harris",
    "Leo": "Martin",
    "Mona": "Thompson",
    "Nina": "Garcia",
    "Oscar": "Martinez",
    "Paul": "Robinson",
    "Quincy": "Clark",
    "Rita": "Rodriguez",
    "Sam": "Lewis",
    "Tina": "Lee",
    "Uma": "Walker",
    "Vince": "Hall",
    "Wendy": "Allen",
    "Xander": "Young",
    "Yara": "Hernandez",
    "Zane": "King",
    "Aaron": "Wright",
    "Bella": "Lopez",
    "Carl": "Hill",
    "Diana": "Scott",
    "Ethan": "Green",
    "Fiona": "Adams",
    "George": "Baker",
    "Holly": "Gonzalez",
    "Ian": "Nelson",
    "Jill": "Carter",
    "Kyle": "Mitchell",
    "Lily": "Perez",
    "Mason": "Roberts",
    "Nora": "Turner",
    "Owen": "Phillips",
    "Piper": "Campbell",
    "Quinn": "Parker",
    "Ryan": "Evans",
    "Sara": "Edwards",
    "Tom": "Collins",
    "Ursula": "Stewart",
    "Victor": "Sanchez",
    "Will": "Morris",
    "Xena": "Rogers",
    "Yvonne": "Reed",
    "Zach": "Cook",
    "Adam": "Morgan",
    "Beth": "Bell",
    "Chris": "Murphy",
    "Dana": "Bailey",
    "Eli": "Rivera",
    "Faith": "Cooper",
    "Gabe": "Richardson",
    "Hannah": "Cox",
    "Isaac": "Howard",
    "Jade": "Ward",
    "Ken": "Torres",
    "Lara": "Peterson",
    "Max": "Gray",
    "Nate": "Ramirez",
    "Olivia": "James",
    "Pete": "Watson",
    "Quentin": "Brooks",
    "Rachel": "Kelly",
    "Steve": "Sanders",
    "Tara": "Price",
    "Ulysses": "Bennett",
    "Vera": "Wood",
    "Walt": "Barnes",
    "Ximena": "Ross",
    "Yosef": "Henderson",
    "Zara": "Coleman",
    "Aiden": "Jenkins",
    "Brianna": "Perry",
    "Connor": "Powell",
    "Daisy": "Long",
    "Evan": "Patterson",
    "Felicity": "Hughes",
    "Gavin": "Flores",
    "Hailey": "Washington",
    "Isaiah": "Butler",
    "Jasmine": "Simmons",
    "Kevin": "Foster",
    "Liam": "Gonzales",
    "Mia": "Bryant",
    "Noah": "Alexander",
    "Omar": "Russell",
    "Paige": "Griffin",
    "Quincy": "Diaz",
    "Riley": "Hayes",
    "Sophia": "Myers",
    "Tyler": "Ford",
    "Uriah": "Hamilton",
    "Violet": "Graham",
    "Wyatt": "Sullivan",
    "Xander": "Wallace",
    "Yasmin": "Woods",
    "Zeke": "Cole",
    "Ava": "West",
    "Blake": "Jordan",
    "Cora": "Owens",
    "Dylan": "Reynolds",
    "Ella": "Fisher",
    "Finn": "Ellis",
    "Grace": "Harrison",
    "Henry": "Gibson",
    "Isla": "McDonald",
    "Jack": "Cruz",
    "Kara": "Marshall",
    "Leo": "Ortiz",
    "Maya": "Gomez",
    "Nolan": "Murray",
    "Olive": "Freeman",
    "Parker": "Wells",
    "Quinn": "Webb",
    "Ruby": "Simpson",
    "Sam": "Stevens",
    "Tess": "Tucker",
    "Umar": "Porter",
    "Vince": "Hunter",
    "Willow": "Hicks",
    "Xena": "Crawford",
    "Yara": "Henry",
    "Zane": "Boyd",
    "Aiden": "Mason",
    "Bella": "Morales",
    "Caleb": "Kennedy",
    "Daisy": "Warren",
    "Eli": "Dixon",
    "Fiona": "Ramos",
    "Gabe": "Reyes",
    "Holly": "Burns",
    "Isaac": "Gordon",
    "Jade": "Shaw",
    "Kyle": "Holmes",
    "Lily": "Rice",
    "Mason": "Robertson",
    "Nora": "Hunt",
    "Owen": "Black",
    "Piper": "Daniels",
    "Quinn": "Palmer",
    "Ryan": "Mills",
    "Sara": "Nichols",
    "Tom": "Grant",
    "Ursula": "Knight",
    "Victor": "Ferguson",
    "Will": "Rose",
    "Xena": "Stone",
    "Yvonne": "Hawkins",
    "Zach": "Dunn",
    "Adam": "Perkins",
    "Beth": "Hudson",
    "Chris": "Spencer",
    "Dana": "Gardner",
    "Eli": "Stephens",
    "Faith": "Payne",
    "Gabe": "Pierce",
    "Hannah": "Berry",
    "Isaac": "Matthews",
    "Jade": "Arnold",
    "Ken": "Wagner",
    "Lara": "Willis",
    "Max": "Ray",
    "Nate": "Watkins",
    "Olivia": "Olson",
    "Pete": "Carroll",
    "Quentin": "Duncan",
    "Rachel": "Snyder",
    "Steve": "Hart",
    "Tara": "Cunningham",
    "Ulysses": "Bradley",
    "Vera": "Lane",
    "Walt": "Andrews",
    "Ximena": "Ruiz",
    "Yosef": "Harper",
    "Zara": "Fox"
}
print(find_last_name(names_dict, "John")) # Doe
print(find_last_name(names_dict, "Jane")) # Smith
print(find_last_name(names_dict, "Mike")) # Jones
print(find_last_name(names_dict, "Alice")) # Brown
